### ISSUE TITLE
grug: bob doesn't support wildcard in workspace member

### ISSUE THREAD

**Issue by larry0x** [left-curve/left-curve#215]
If the workspace members is something like:

```toml
[workspace]
members = ["contracts/*"]
```

Then bob doesn't work. We need to expand the path using `glob`.
